<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-D2BFLFER" failures="0" tests="43" name="api.DepositApiTest" time="12.319" errors="4" timestamp="25 Jul 2019 07:31:03 GMT">
  <testcase classname="api.DepositApiTest" name="depositTransactionDepositPost" time="0.412"/>
  <testcase classname="api.DepositApiTest" name="depositVaccountTdAccountTypePost" time="0.123"/>
  <testcase classname="api.DepositApiTest" name="depositVcustomerEmailFormatPost" time="0.095"/>
  <testcase classname="api.DepositApiTest" name="depositVaccountAccountBalancePost" time="0.161"/>
  <testcase classname="api.DepositApiTest" name="depositTermDepositTermDepositEnquiryPost" time="0.257"/>
  <testcase classname="api.DepositApiTest" name="depositFeAccountOpeningPost" time="1.209"/>
  <testcase classname="api.DepositApiTest" name="depositVaccountCurrencyGet" time="0.091"/>
  <testcase classname="api.DepositApiTest" name="depositCusMainCustContactInfoUpdatePost" time="0.409"/>
  <testcase classname="api.DepositApiTest" name="depositTermDepositTermDepositRenewalPost" time="0.169">
    <error message="expected [200] but found [202]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [200] but found [202]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:370)
	at org.testng.Assert.assertEquals(Assert.java:380)
	at api.DepositApiTest.depositTermDepositTermDepositRenewalPost(DepositApiTest.java:385)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:38)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:382)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:835)
]]>
    </error>
  </testcase> <!-- depositTermDepositTermDepositRenewalPost -->
  <testcase classname="api.DepositApiTest" name="depositAccountOpeningAccountCreationPost" time="0.420"/>
  <testcase classname="api.DepositApiTest" name="depositVaccountSavOrCurTypePost" time="0.113"/>
  <testcase classname="api.DepositApiTest" name="depositVaccountAccountNumberExistsPost" time="0.165"/>
  <testcase classname="api.DepositApiTest" name="depositVaccountStockAccountTypePost" time="0.111"/>
  <testcase classname="api.DepositApiTest" name="depositVtransactionDateFormatGet" time="0.092"/>
  <testcase classname="api.DepositApiTest" name="depositMetAccountOpeningPost" time="0.422"/>
  <testcase classname="api.DepositApiTest" name="depositVtermDepositTdNumberExistsGet" time="0.183"/>
  <testcase classname="api.DepositApiTest" name="depositCurrentAccountOpeningPost" time="0.600"/>
  <testcase classname="api.DepositApiTest" name="depositAccountEnquiryAccountDetailsGet" time="0.404"/>
  <testcase classname="api.DepositApiTest" name="depositCusMainCustomerCreationPost" time="0.410"/>
  <testcase classname="api.DepositApiTest" name="depositVaccountFundAccountTypePost" time="0.110"/>
  <testcase classname="api.DepositApiTest" name="depositTdAccountOpeningPost" time="0.420"/>
  <testcase classname="api.DepositApiTest" name="depositTermDepositAllTermDepositGet" time="0.485"/>
  <testcase classname="api.DepositApiTest" name="depositTransactionLogEnquiryPost" time="0.443"/>
  <testcase classname="api.DepositApiTest" name="depositVaccountFexAccountTypePost" time="0.111"/>
  <testcase classname="api.DepositApiTest" name="depositVaccountAssociatedAccountsPost" time="0.169"/>
  <testcase classname="api.DepositApiTest" name="depositAccountEnquiryPost" time="0.140">
    <error message="expected [200] but found [400]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [200] but found [400]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:370)
	at org.testng.Assert.assertEquals(Assert.java:380)
	at api.DepositApiTest.depositAccountEnquiryPost(DepositApiTest.java:88)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:38)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:382)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:835)
]]>
    </error>
  </testcase> <!-- depositAccountEnquiryPost -->
  <testcase classname="api.DepositApiTest" name="depositTransactionTransferPost" time="0.473"/>
  <testcase classname="api.DepositApiTest" name="depositTermDepositTermDepositApplicationPost" time="0.767"/>
  <testcase classname="api.DepositApiTest" name="depositVaccountMetAccountTypePost" time="0.106"/>
  <testcase classname="api.DepositApiTest" name="depositVaccountAmountFormatPost" time="0.112"/>
  <testcase classname="api.DepositApiTest" name="depositAccountMaintenanceAccountClosureGet" time="0.411"/>
  <testcase classname="api.DepositApiTest" name="depositAccountEnquiryAllAccountGet" time="0.553">
    <error message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at common.JsonSchemaUtils.assertJsonSchema(JsonSchemaUtils.java:34)
	at common.JsonSchemaUtils.assertResponseJsonSchema(JsonSchemaUtils.java:40)
	at api.DepositApiTest.depositAccountEnquiryAllAccountGet(DepositApiTest.java:111)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:38)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:382)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:835)
]]>
    </error>
  </testcase> <!-- depositAccountEnquiryAllAccountGet -->
  <testcase classname="api.DepositApiTest" name="depositSavingAccountOpeningPost" time="0.503"/>
  <testcase classname="api.DepositApiTest" name="depositVtransactionTransTypeGet" time="0.119"/>
  <testcase classname="api.DepositApiTest" name="depositVcustomerPhoneNumberFormatGet" time="0.091"/>
  <testcase classname="api.DepositApiTest" name="depositTransactionWithdrawalPost" time="0.310"/>
  <testcase classname="api.DepositApiTest" name="depositTermDepositAllEnquiryCustomerNumberGet" time="0.386"/>
  <testcase classname="api.DepositApiTest" name="depositTransactionChequeBookCreationPost" time="0.224"/>
  <testcase classname="api.DepositApiTest" name="depositVcustomerIdFormatGet" time="0.082"/>
  <testcase classname="api.DepositApiTest" name="depositVaccountCurAccountTypePost" time="0.096"/>
  <testcase classname="api.DepositApiTest" name="depositVcustomerExistingCustomerGet" time="0.104"/>
  <testcase classname="api.DepositApiTest" name="depositTermDepositTermDepositDrawDownPost" time="0.160">
    <error message="expected [200] but found [202]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [200] but found [202]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:370)
	at org.testng.Assert.assertEquals(Assert.java:380)
	at api.DepositApiTest.depositTermDepositTermDepositDrawDownPost(DepositApiTest.java:353)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:38)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:382)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:835)
]]>
    </error>
  </testcase> <!-- depositTermDepositTermDepositDrawDownPost -->
  <testcase classname="api.DepositApiTest" name="depositVtermDepositContractPeriodGet" time="0.098"/>
</testsuite> <!-- api.DepositApiTest -->
